# Generated by Django 5.2.7 on 2025-11-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment_management_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=100)),
                ('assignment_description', models.TextField()),
                ('assignment_file', models.FileField(upload_to='assignment_files/')),
                ('assignment_due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Assignment_management_project_app.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Assignment_management_project_app.teacher')),
            ],
        ),
    ]
