# Generated by Django 5.2.7 on 2025-11-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment_management_project_app', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_file', models.FileField(upload_to='submit_file/')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Assignment_management_project_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Assignment_management_project_app.student')),
            ],
        ),
    ]
